in1.in:
  subtaskId: 0
  score: 33

in2.in:
  subtaskId: 0
  score: 33

in3.in:
  subtaskId: 0
  score: 33

in4.in:
  subtaskId: 0
  score: 33

in5.in:
  subtaskId: 0
  score: 33

in6.in:
  subtaskId: 0
  score: 33

in7.in:
  subtaskId: 0
  score: 33

in8.in:
  subtaskId: 0
  score: 33

in9.in:
  subtaskId: 0
  score: 33

in10.in:
  subtaskId: 0
  score: 33

in11.in:
  subtaskId: 0
  score: 33

in12.in:
  subtaskId: 0
  score: 33

in13.in:
  subtaskId: 0
  score: 33

in14.in:
  subtaskId: 0
  score: 33

in15.in:
  subtaskId: 0
  score: 33

in16.in:
  subtaskId: 0
  score: 33

in17.in:
  subtaskId: 0
  score: 33

in18.in:
  subtaskId: 0
  score: 33

in19.in:
  subtaskId: 0
  score: 33

in20.in:
  subtaskId: 0
  score: 33

in21.in:
  subtaskId: 1
  score: 33

in22.in:
  subtaskId: 1
  score: 33

in23.in:
  subtaskId: 1
  score: 33

in24.in:
  subtaskId: 1
  score: 33

in25.in:
  subtaskId: 1
  score: 33

in26.in:
  subtaskId: 1
  score: 33

in27.in:
  subtaskId: 1
  score: 33

in28.in:
  subtaskId: 1
  score: 33

in29.in:
  subtaskId: 1
  score: 33

in30.in:
  subtaskId: 1
  score: 33

in31.in:
  subtaskId: 2
  score: 34

in32.in:
  subtaskId: 2
  score: 34

in33.in:
  subtaskId: 2
  score: 34

in34.in:
  subtaskId: 2
  score: 34

in35.in:
  subtaskId: 2
  score: 34

in36.in:
  subtaskId: 2
  score: 34

in37.in:
  subtaskId: 2
  score: 34

in38.in:
  subtaskId: 2
  score: 34

in39.in:
  subtaskId: 2
  score: 34

in40.in:
  subtaskId: 2
  score: 34

